= Setting up linting
:sourcedir: ../

oxlint is a static code analysis tool for identifying problematic patterns in JavaScript and TypeScript code.

oxlint is part of the same Oxc toolchain that powers tsdown, implements the most common ESLint (and typescript-eslint) rules, and lints TypeScript natively — without depending on the `typescript` package. Having linting as a part of the build process is considered a good practice.

== Install

[source, Terminal]
----
npm install --save-dev oxlint
----

== Configure

=== package.json

Add the following scripts to the package.json file:

[source, JSON]
----
{
  "scripts": {
    "check": "concurrently -c auto -g --timings npm:check:types npm:lint",
    "lint": "oxlint src",
  }
}
----

TIP: Note that `check` command was added to package.json in the previous chapter about type checking. Here we just modify it to execute linting as a part of the `check` command.

=== .oxlintrc.json

Create the following file:

..oxlintrc.json
[source, JSON]
----
include::{sourcedir}.oxlintrc.json[]
----

Linting will now be executed as a part of the `check` command and, therefore, as a part of the build process.

== Summary

Now, you have activated linting - and only one step remains.
Prepare your project for <<test#,testing>>.
